version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.production
    image: ${DOCKER_IMAGE_NAME:-laravel-app}:latest
    container_name: laravel-app
    restart: unless-stopped
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    ports:
      - "${APP_PORT:-80}:80"
    volumes:
      - ./storage:/var/www/html/storage
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    depends_on:
      - database
      - redis
    networks:
      - laravel

  database:
    image: postgres:17
    container_name: laravel-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE:-laravel}
      POSTGRES_USER: ${DB_USERNAME:-laravel}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "${FORWARD_DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - laravel

  redis:
    image: redis:7-alpine
    container_name: laravel-redis
    restart: unless-stopped
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
    driver: bridge